{% set version = "0.0.3d2" %}

package:
  name: numkl
  version: {{ version }}
source:
  url: https://github.com/refraction-ray/numkl/archive/v{{ version }}.tar.gz
build:
  number: 3
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  script_env:
    - MKLROOT
requirements:
  build:
    - python 
    - {{ compiler('c') }}
    - setuptools
    - mkl-devel
    - cython 
    - numpy 
  host:
    - python
    - setuptools
    - mkl-devel
    - cython 
    - numpy 
  run:
    - python
    - mkl
    - {{ pin_compatible('numpy') }}
test:
 imports:
   - numkl
   - numkl.ev
   - numkl.eig
about:
  home: https://github.com/refraction-ray/numkl
  license: MIT
  summary: A thin cython/python wrapper on some routines from Intel MKL

extra:
  recipe-maintainers:
    - refraction-ray
