# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NQb+Sol7e3uh9s7RdBGh1ZL23QEgIvSzSbI4zTiZgUg/NlKKcmBjHWQ7Me2yB+Jke9fU5NVgpH1FygVhdODFVr92vjHOb2wysom7NLowiQriz/y5AO23VfEYh4sBXZYNWs305FqYRrShOi701ZCL7KoIJeTeOokcstRZOkL0rrKo1qxb/R0frWZx6fTI7XJnM1nelChxVek5cCXjGL/zFL1OJaPNe4W+izW4O5/hwYuC82wIi5IAIc70tU7HTOK2QAsFwk+wIKGf6eGbJM/7TjjxiHtEcO0B2q/B6Y+dr/jo0yaAKxcCVPh3H6LBI+WEbNXfL6ethEFCVR7DRKjyLqgrfVRuMBVeHAsOibRhYRk4JC+dYcneuAGBWv02YF6qHRJ0CeD2Fi6LdhWqSdTan/0TainqHxrA+c/kJEHEd66ceN9gJQ8P+DeWtIXkNX1v6habFCkN4AagnABNzdmJ3VERh+XJfiZLJD6auTyiWHL79dlE9/oWeWfMlwQiErVytelEtE2x+7JJXfR+Q6HMpgMQnk42R8hYMjJHIMkGKKKV/WTdAZ2lyhCBfkKhYxqeBroO+dcbof5jmlRdBS7dxezVaLne/yD18eqPcqE+tA13yLHNjQNT0TeojIFTTqssJtFNWtNgnd6UztNsYcCDBQB82RhPvumQ/fJ1K+sBLxE="

matrix:
  include:
    - env: CONFIG=linux_ UPLOAD_PACKAGES=True PLATFORM=linux-64 DOCKER_IMAGE=condaforge/linux-anvil-comp7
      os: linux

    - env: CONFIG=osx_ UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:
  - export CI=travis

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi

  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.travis/run_docker_build.sh; fi