travis:
  secure:
    BINSTAR_TOKEN: NQb+Sol7e3uh9s7RdBGh1ZL23QEgIvSzSbI4zTiZgUg/NlKKcmBjHWQ7Me2yB+Jke9fU5NVgpH1FygVhdODFVr92vjHOb2wysom7NLowiQriz/y5AO23VfEYh4sBXZYNWs305FqYRrShOi701ZCL7KoIJeTeOokcstRZOkL0rrKo1qxb/R0frWZx6fTI7XJnM1nelChxVek5cCXjGL/zFL1OJaPNe4W+izW4O5/hwYuC82wIi5IAIc70tU7HTOK2QAsFwk+wIKGf6eGbJM/7TjjxiHtEcO0B2q/B6Y+dr/jo0yaAKxcCVPh3H6LBI+WEbNXfL6ethEFCVR7DRKjyLqgrfVRuMBVeHAsOibRhYRk4JC+dYcneuAGBWv02YF6qHRJ0CeD2Fi6LdhWqSdTan/0TainqHxrA+c/kJEHEd66ceN9gJQ8P+DeWtIXkNX1v6habFCkN4AagnABNzdmJ3VERh+XJfiZLJD6auTyiWHL79dlE9/oWeWfMlwQiErVytelEtE2x+7JJXfR+Q6HMpgMQnk42R8hYMjJHIMkGKKKV/WTdAZ2lyhCBfkKhYxqeBroO+dcbof5jmlRdBS7dxezVaLne/yD18eqPcqE+tA13yLHNjQNT0TeojIFTTqssJtFNWtNgnd6UztNsYcCDBQB82RhPvumQ/fJ1K+sBLxE=
github:
  user: refraction-ray
channels:
  targets:
  - [refraction-ray, main]
provider:
  linux: travis
  osx: travis
  win: None
