travis:
  secure:
    BINSTAR_TOKEN: JM8yq0tFNNdG7KkOeq1DZfEk1qMYvSye4mSIjQlzd9zNDRy+3QJScg12ED9If1s+3P5O8uzAkuui5e5SoTFCPdao/EqtyO19RlT3RV5tmMWt8kLb1sBAO+TM5K3UE51g04hK4VxBGBUvV2o2f3UmOZuln+ZOKdHIHZYMNDiW16vwfrl2R+wYsGfGGd5psSJxi1nE8HuJln9GVAUuGlBR0GMLOVvM3EyOBVrv7ArbmkJAbPy5gQmboo22kcvgV7gGyd0J5TxpJ+Mhe6GXQxb0KCqW5ilpa0lsgQbUewso0kFXE0RVvTm1D0SsgjU+JXr9xOJUdX6z5Z6a/Z5LdItCtaZVF+AZbglDWPC1wX+iohwbMDl0KWWMcOCZ6Gt38MlfBkBsyGwrcGB6eVo9ZCr1GT5n5KE6xNNLxVfA474KQKHrCB5Zmv9u6K0dlBeL3/C7PdBIKGghMewq8SephYpBpMwBfK1smvDVtLXs+kouA5ZTJ5WgsYZvoP1ppVJW1Y1X0cRO71F6DFWzaVCeoYo2TXrNQcadt/nuMyYC/AVNRtuWgH4p9fc9MWQwwQQac5QfY6KeQwFX693lAxikPNQfqoTLvX+0Y0d93UdzBcGBaADzsoVzGpHw5CzyVEiDCaRStPOZYGd3xcJnmSDd/9y6Xh6/0yvK36ayVr0hoeJLFQA=
github:
  user: refraction-ray
channels:
  targets:
    - ["refraction-ray", "main"]
provider:
  linux: travis
  osx: None
  win: None
