travis:
  secure:
    BINSTAR_TOKEN: IVi/itBtN7yAnqHqS5+lyEKjiwCr495y5iCWWZMN8TFg93hCvGP/VSiGcvwYZWH5Av0JXivqoS6ELBgnXGKt6lG4Oc6OQ9CCGKzQhIBn/Pf51wk7B/3h0VarbhJuQ3xm0oJoQLB15BfZ7doJ6V+dVqw71Q2xhXUp/VGiBASyp2kaiZFOc1Z85t++dXZFWcv+aZyPx6mIPdTu4NYZJ1RRAo0N9/UpR7ES0CxkVSI7nMEijkAELrU0cS4T8+QNwuYiiaFxTjVkf2JIruU4sJoM6KkRK8w8Mr1iw2aLe+ExG8Qvii6T5ZtoOtYE7TM3J1YeuQLTa8hjL7lO23UQQ/bJFSUvylc+y7lex2cAsgy1OGQ4/TG81YybAfKpZtYm7BmHJVrtA0lt8XmXOYu5xqSeG6bI6y43q8cdWxHOhhF7qWHHl5WiV27yeXs4SO952W0dFmTh+0p0PrJ+WZzFnDkmQVit+a37XPWIK25Q7s3ZRGiJft+jItIvbdgA9RdqgvI+/VccVm+/2ScgGEoX3lT4wwBMl9S0/DeZLnZ2tjA40w6vLEsjZhAkxDsZe+kzUrQ+MIr6MQRm7ghPfhjh067a278XNgElT/nORTQSwJ9JdmgAmRTC7BpCIHkZ7xlaPhL3Ipx/H++36gZi7JlEfNwDXy7SdsFMoTqOluvkf/sdatk=
github:
  user: refraction-ray
channels:
  targets:
  - [refraction-ray, main]
provider:
  linux: travis
  osx: None
  win: None
